/*contract - id, name, description, code, budget, commited_cost, forecast, paid, completion_percentage, vendor_id, project_id
project - id, name, description, code, start_date, end_date, owner_id
user - id, username, first name, last name, email
vendor - vendor_id, vendor_name, vendor_address*/

CREATE SEQUENCE VENDOR_SERIAL INCREMENT BY 1 START WITH 1 CACHE 5;
CREATE SEQUENCE USER_SERIAL INCREMENT BY 1 START WITH 1 CACHE 5;
CREATE SEQUENCE PROJECT_SERIAL INCREMENT BY 1 START WITH 1 CACHE 5;
CREATE SEQUENCE CONTRACT_SERIAL INCREMENT BY 1 START WITH 1 CACHE 5;


CREATE TABLE USER_INFO (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('USER_SERIAL'),
	USERNAME VARCHAR(64) NOT NULL UNIQUE,
	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE VENDOR (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('VENDOR_SERIAL'),
	NAME VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE PROJECT (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('PROJECT_SERIAL'),
	NAME VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(256),
	START_DATE DATE,
	END_DATE DATE,
	OWNER_ID INTEGER references USER_INFO(ID)
);

CREATE TABLE CONTRACT (
	ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('CONTRACT_SERIAL'),
	NAME VARCHAR(128) NOT NULL,
	DESCRIPTION VARCHAR(256),
	CODE VARCHAR(16),
	BUDGET NUMERIC(10,2),
	COMMITTED_COST NUMERIC(10,2),
	FORECAST NUMERIC(10,2),
	PAYMENT NUMERIC(10,2),
	COMPLETION_PERCENTAGE INTEGER,
	VENDOR_ID INTEGER REFERENCES VENDOR(ID),
	PROJECT_ID INTEGER REFERENCES PROJECT(ID)
);

INSERT INTO USER_INFO (USERNAME, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('jdoe', 'John', 'Doe', 'jdoe@gmail.com');
INSERT INTO USER_INFO (USERNAME, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('rsmith', 'Rosie', 'smith', 'rsmith@gmail.com');

INSERT INTO VENDOR(NAME) VALUES ('GE Electrical');
INSERT INTO VENDOR(NAME) VALUES ('Gator Security Systems');
INSERT INTO VENDOR(NAME) VALUES ('Ricochet Design Center');
INSERT INTO VENDOR(NAME) VALUES ('Abacus Granite');
INSERT INTO VENDOR(NAME) VALUES ('ARC Software Systems');
INSERT INTO VENDOR(NAME) VALUES ('Empire Webdesign');
INSERT INTO VENDOR(NAME) VALUES ('Maya Photorealistic Systems'); 
INSERT INTO VENDOR(NAME) VALUES ('Ubisoft Systems'); 

INSERT INTO PROJECT(NAME, DESCRIPTION, START_DATE, END_DATE, OWNER_ID) VALUES 
('Bay Bridge Traffic Simulation', 'Simulate the impact traffic during different hours of the day', '2016-03-19', '2016-05-20', 1);

INSERT INTO PROJECT(NAME, DESCRIPTION, START_DATE, END_DATE, OWNER_ID) VALUES 
('Angry Birds Movie Website', 'Create a website for the Angry Birds Movie', '2016-04-01', '2016-05-01', 1);

INSERT INTO PROJECT(NAME, DESCRIPTION, START_DATE, END_DATE, OWNER_ID) VALUES 
('Holland Park', 'Construction of the new park in San Francisco', '2016-05-01', '2016-11-15', 2);

INSERT INTO PROJECT(NAME, DESCRIPTION, START_DATE, END_DATE, OWNER_ID) VALUES 
('Broadway Warehouse', 'Construction of the new warehouse for housing electrical equipment', '2016-02-11', '2016-07-17', 2);

---------------------

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Park Lighting', 'Lighting in the park', 'LGHT', 2500, 2000, 1800, 500, 25, 1, 3);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Park Flooring', 'Rubber tiles, and other granite structures in the park', 'FLR', 5000, 4500, 4300, 1500, 40, 4, 3);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Park design', 'Designing the layout, and different play structures', 'DSGN', 3000, 2500, 2000, 500, 90, 3, 3);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Park 3D views', 'Generate photo realistic views of the park for project stakeholders', 'PRL', 1000, 999, 700, 500, 40, 7, 3);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Angry Birds website design', 'Design the website for Anygry Birds', 'DSGN', 2500, 2000, 1800, 1700, 90, 6, 2);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Angry Birds website implementation', 'Implement the website for Angry Birds', 'BLD', 5000, 4500, 4500, 3500, 40, 5, 2);

INSERT INTO CONTRACT (NAME, DESCRIPTION, CODE, BUDGET, COMMITTED_COST, FORECAST, PAYMENT, COMPLETION_PERCENTAGE, VENDOR_ID, PROJECT_ID) VALUES
('Angry Birds game', 'Promotion game on website for Angry Birda movie', 'BLD', 3500, 3300, 3300, 1500, 35, 8, 2);

DROP TABLE CONTRACT;
DROP TABLE PROJECT;
DROP TABLE VENDOR;
DROP TABLE USER_INFO;
DROP SEQUENCE VENDOR_SERIAL;
DROP SEQUENCE CONTRACT_SERIAL;
DROP SEQUENCE PROJECT_SERIAL;
DROP SEQUENCE USER_SERIAL;
